### ISSUE TITLE
[110 EUR]: Approval Single Request: money to print zine 

### ISSUE THREAD

**Issue by berlin-pyladies** [PyLadiesGermany/PySV_PyLadies_fund#11]
### Chapter Name

PyLadies Berlin (though content is chapter agnostic)

### Added chapter name as a label and requested amount in title

- [X] confirm

### Name of person submitting request

Jessica

### Amount in EURs being requested

100

### Date of event *(if applicable)*

2024-05-20

### Reason for request

Requesting money to be able to print copies of the PyLadies Zine for PyCon DE PyData Berlin 2024. It will be circa 50-75 colour copies and 10-20 black and white copies to be distributed during the conference.

### Approvals

- [x] Approval 1: laysauchoa
- [x] Approval 2: @discombobulateme 

### Post Approval Actions

- [x] Email your invoice to: [invoice@python-verband.org](mailto:invoice@python-verband.org) with pyladies@python-verband.org in CC (you can find a template email in this [repo](./Docs/email_templates.md)).
- [x] Add the label `invoice submitted` to this issue
- [x] Once the invoice has been paid, add the label `invoice_paid` to this issue & move issue to completed requests

**Comment by laysauchoa** [comment]
Hi, is this about flyers for the conference? @sleepypioneer

**Comment by berlin-pyladies** [comment]
![image](https://github.com/PyLadiesGermany/PySV_PyLadies_fund/assets/154543209/a37f788d-bd68-4ddf-bed9-d0b4da597f9e)

I will print on Saturday at the local print shop. It will be a foldable zine following this type of design. We have been brainstorming here https://miro.com/app/board/uXjVNh3eu34=/ and will put it together here on canva https://www.canva.com/design/DAF_VDVVUQk/wlmf3BbHeq0M4E6CsM6l9A/edit

**Comment by laysauchoa** [comment]
@sleepypioneer I do not have access to this miro board and I may have missed the discussion about this on the slack channel, can you please, point me where did they started? Maybe some of my questions are answered there already, if not:

- do each chapter gets a space or a number of pages where they can show their chapter? 
- were other chapters requested participation?
- who decides the content?

I understand the time is short but since this requests is titled PyLadies Germany, I'd like to understand a bit more.

**Comment by laysauchoa** [comment]
I've got access to the content now and I see it can be potentially focusing on PyLadies Berlin if I understood correct. I think it would make more sense to have titled as **PyLadies Germany** when is a general resource which all chapters could potentially use for their chapters or promote their chapters equally.

**Comment by berlin-pyladies** [comment]
@laysauchoa  fair enough, I will change this to be under Berlin instead :) Definitely it would have been nice to have more participation from other chapters, it was first raised in the general [pyladies at Pycon channel](https://pyladies.slack.com/archives/C037UFWDZ6X/p1707247741423659?thread_ts=1707164167.481209&cid=C037UFWDZ6X) but most interest came from other Berlin chapter members which is why this then became more skewed in that direction (but also definitely I could have made more effort to include more folks - that is my fault), also as you mention time is a factor. The idea however is to have it more chapter agnostic, and conference focused with the main point of distribution being the PyLadies Booth at the 2024 conference (any left over copies can be shared between chapters present 🙂 )

We are currently discussing the zine creation [here in slack](https://pyladies.slack.com/archives/C06P03ZKKGE) incase you would like to join :)

**Comment by laysauchoa** [comment]
@sleepypioneer thanks, Jessica! Makes sense, I am adding approval, and I think it will look great. It inspired me to make such flyer in the future as well. I missed this year, but hope next year I can help more.

**Comment by berlin-pyladies** [comment]
The final cost for this was 110 just FYI
