### ISSUE TITLE
[150 EUR]: Instant Approval Request

### ISSUE THREAD

**Issue by cmaureir** [PyLadiesGermany/PySV_PyLadies_fund#12]
### Chapter Name

PyLadies Berlin

### Added chapter name as a label and requested amount in title

- [X] confirm

### Name of person submitting request

Cristián Maureira-Fredes

### Amount in EURs being requested

150

### Item being requested

- [X] Up to 200 EUR for stickers per chapter per calendar year
- [ ] A roll-up banner (one-time purchase) for a chapter
- [ ] Shared subscriptions - i.e. Restream/ Lastpass (these subscriptions should have been agreed upon by the chapters beforehand)

### Item details

Two sets of stickers (100 of each) with the heart-shaped one, and a new design for the letters-only. 
![Screenshot 2024-05-13 at 14-18-35 Bestellbestätigung #2941949 - cmaureirafredes@gmail com - Gmail](https://github.com/PyLadiesGermany/PySV_PyLadies_fund/assets/177982/0a53bb6d-77e8-4c2a-a242-2618e4ff3e34)

### Post Approval Actions

- [x] Email your invoice to: [invoice@python-verband.org](mailto:invoice@python-verband.org) with pyladies@python-verband.org in CC (you can find a template email in this [repo](./Docs/email_templates.md)).
- [x] Add the label `invoice submitted` to this issue
- [x] Once the invoice has been paid, add the label `invoice_paid` to this issue & move issue to completed requests

**Comment by berlin-pyladies** [comment]
closing as now complete. Some fixes for the process raised in #13
