### ISSUE TITLE
110 EUR: Approval Multi Request Canva PRO

### ISSUE THREAD

**Issue by laysauchoa** [PyLadiesGermany/PySV_PyLadies_fund#17]
### Chapter Name

PyLadies Munich

### Added chapter name as a label and requested amount in title

- [X] confirm

### Name of person submitting request

@laysauchoa

### Amount in EURs being requested

110

### Reason for request

Canva PRO subscription to help create with manage visuals for the chapter

### Approvals

- [ ] Approval 1: <name-of-approver>
- [ ] Approval 2: <name-of-approver>

### Items purchased

Email your invoices to: [invoice@python-verband.org](mailto:invoice@python-verband.org) with pyladies@python-verband.org in CC (you can find a template email in this [repo](./Docs/email_templates.md)).
| Item                     | Purpose                                   | Amount  (EUR)     |
| ------------------------ | ----------------------------------------- | ----------------- |
|                          |                                           |                   |
|                          |                                           |                   |
|                          |                                           |                   |

### After full amount spent

- [ ] Add the label `invoice_submitted` and `request_complete`` to this issue
- [ ] Once all invoices have been paid, add the label `invoice_paid` to this issue & move the ticket to completed requests

### Additional Information

https://www.canva.com/pro/#pricing

**Comment by sleepypioneer** [comment]
Could this be used by other chapters @laysauchoa ? It could then be under the Germany chapter and adding to our tooling? For this single item you could have used the Single request but it doesn't really matter at this point. Any feedback you have on the process is appreciated, I already have some in an [issue](https://github.com/PyLadiesGermany/PySV_PyLadies_fund/issues/13) here to work on

**Comment by laysauchoa** [comment]
Hi @sleepypioneer it is slightly cheaper per group per e-mail but not much cheaper, so it is easier to keep separate. So if a specific chapter needs, they can request and manage the accounts and invoices. Ah, okay, cool, I will open in a new issue.
