### ISSUE TITLE
110 EUR: Approval Single Request Canva PRO

### ISSUE THREAD

**Issue by laysauchoa** [PyLadiesGermany/PySV_PyLadies_fund#18]
### Chapter Name

PyLadies Munich

### Added chapter name as a label and requested amount in title

- [X] confirm

### Name of person submitting request

@laysauchoa

### Amount in EURs being requested

110

### Reason for request

Canva PRO 110 EUR to help manage visual aids for the chapter.

### Approvals

- [x] Approval 1: @sleepypioneer (on behalf on approval group)

### Post Approval Actions

- [x] Email your invoice to: [invoice@python-verband.org](mailto:invoice@python-verband.org) with pyladies@python-verband.org in CC (you can find a template email in this [repo](./Docs/email_templates.md)).
- [x] Add the label `invoice submitted` to this issue
- [x] Once the invoice has been paid, add the label `invoice_paid` to this issue & move issue to completed requests

### Additional Information

https://www.canva.com/pro/#pricing

**Comment by sleepypioneer** [comment]
Makes sense to me @laysauchoa to do this per account as you mentioned and sounds good to me. In the guidelines I would not be giving official approval but if we are struggling to get two perhaps we can discuss changing that as personally for this I would think it should even be fine for you to do without approval.

**Comment by laysauchoa** [comment]
@sleepypioneer thanks for the approval, and caring. Can we make it this without approval in the guidelines? I'd see this more like basic tools with reasonable price.

**Comment by sleepypioneer** [comment]
Yes agree please go ahead and consider approved

**Comment by berlin-pyladies** [comment]
@laysauchoa any further help needed here? No invoice has been sent with [pyladies@python-verband.org](mailto:pyladies@python-verband.org) in CC yet.

**Comment by laysauchoa** [comment]
I sigend up today and I am waiting for the invoice to be generated after the free trial (30 days), and then I will send to the PSV.

**Comment by alanderex** [comment]
Invoice received, reimbursement processed.

**Comment by laysauchoa** [comment]
I am closing this issue as the reimbursement is complete. Thank you @alanderex @sleepypioneer
