### ISSUE TITLE
[85,81 EUR]: Approval Single Request 

### ISSUE THREAD

**Issue by becklady** [PyLadiesGermany/PySV_PyLadies_fund#19]
### Chapter Name

PyLadies Berlin

### Added chapter name as a label and requested amount in title

- [X] confirm

### Name of person submitting request

Vanessa Fonseca

### Amount in EURs being requested

85,81

### Date of event *(if applicable)*

2024-06-24

### Reason for request

Payment for drinks for the July 2024 event - Pyladies Berlin (I was not informed that I needed to request this before making the purchase.)
[Rechnung 123686710.pdf](https://github.com/user-attachments/files/16234769/Rechnung.123686710.pdf)

### Approvals

- [ ] Approval 1: <name-of-approver>
- [ ] Approval 2: <name-of-approver>

### Post Approval Actions

- [X] Email your invoice to: [invoice@python-verband.org](mailto:invoice@python-verband.org) with pyladies@python-verband.org in CC (you can find a template email in this [repo](./Docs/email_templates.md)).
- [ ] Add the label `invoice submitted` to this issue
- [ ] Once the invoice has been paid, add the label `invoice_paid` to this issue & move issue to completed requests

### Additional Information

The event was in the spiced academy

**Comment by berlin-pyladies** [comment]
This will go out of money that was added to the fund on Jessica's behalf (as reimbursement for some work) as an exception to the rule because it was not submitted before the money was spent.

**Comment by berlin-pyladies** [comment]
@becklady the invoice has not been sent to [pyladies@python-verband.org](mailto:pyladies@python-verband.org) though this step was ticked could you please check?

**Comment by alanderex** [comment]
@becklady We have received the email and receipt and would be happy to process it.
We do miss any details to where to reimburse to.
Could you please send your bank details for the reimbursement by email? 🙏

**Comment by becklady** [comment]
Sent! Thanks @alanderex

**Comment by alanderex** [comment]
reimbursement made.
