### ISSUE TITLE
[177,80 EUR]: Approval Single Request - Train to PyConDE 2024

### ISSUE THREAD

**Issue by terezaif** [PyLadiesGermany/PySV_PyLadies_fund#20]
### Chapter Name

PyLadies Hamburg

### Added chapter name as a label and requested amount in title

- [X] confirm

### Name of person submitting request

Tereza Iofciu

### Amount in EURs being requested

177,80

### Date of event *(if applicable)*

2024-04-22

### Reason for request

Travel to Berlin for PyConDE as speaker and organizer

### Approvals

- [x] Approval 1: @discombobulateme  
- [x] Approval 2: @laysauchoa 

### Post Approval Actions

- [x] Email your invoice to: [invoice@python-verband.org](mailto:invoice@python-verband.org) with pyladies@python-verband.org in CC (you can find a template email in this [repo](./Docs/email_templates.md)).
- [x] Add the label `invoice submitted` to this issue
- [x] Once the invoice has been paid, add the label `invoice_paid` to this issue & move issue to completed requests

**Comment by sleepypioneer** [comment]
technically I am not really giving an approval and act more as a facilitator. As you are one of the fund board members you could also be a second approval. However if it's blocking and taking too much time to get any approval then I can give mine. (The main thing is we spend the money!)

**Comment by alanderex** [comment]
Reimbursement made.

**Comment by terezaif** [comment]
Wee! So fast! Thanks!
