### ISSUE TITLE
[178.38 EUR]: Instant Approval Request

### ISSUE THREAD

**Issue by berlin-pyladies** [PyLadiesGermany/PySV_PyLadies_fund#22]
### Chapter Name

PyLadies Germany

### Added chapter name as a label and requested amount in title

- [X] confirm

### Name of person submitting request

Jessica and Tereza

### Amount in EURs being requested

178.38

### Item being requested

- [ ] Up to 200 EUR for stickers per chapter per calendar year
- [ ] A roll-up banner (one-time purchase) for a chapter
- [X] Shared subscriptions - i.e. Restream/ Lastpass (these subscriptions should have been agreed upon by the chapters beforehand)

### Item details

We want to have a zoom account so we can hold online events in zoom. We also plan to potentially share this account outside the current chapters to encourage more folks to hold online events.

### Post Approval Actions

- [ ] Email your invoice to: [invoice@python-verband.org](mailto:invoice@python-verband.org) with pyladies@python-verband.org in CC (you can find a template email in this [repo](./Docs/email_templates.md)).
- [ ] Add the label `invoice submitted` to this issue
- [ ] Once the invoice has been paid, add the label `invoice_paid` to this issue & move issue to completed requests

### Additional Information

This was discussed in slack here https://pyladies.slack.com/archives/C02EP22BBTN/p1722591145064339

**Comment by laysauchoa** [comment]
Nice, is the Lastpass accessible by all chapters? Thanks!

**Comment by berlin-pyladies** [comment]
currently there can only be 5 members in the family but we can share a password with the other chapters. Ultimately we would like to switch from LastPass (which @sleepypioneer paid for) to something all chapters have access to and works more efficiently for us all :)
