### ISSUE TITLE
[144EUR]: Approval Single Request

### ISSUE THREAD

**Issue by berlin-pyladies** [PyLadiesGermany/PySV_PyLadies_fund#23]
### Chapter Name

PyLadies Berlin, PyLadies Hamburg

### Added chapter name as a label and requested amount in title

- [X] confirm

### Name of person submitting request

Jessica and Tereza

### Amount in EURs being requested

144

### Date of event *(if applicable)*

2024-08-29

### Reason for request

Requesting money for purchasing books to raffle during meetup. Getting 50% discount from the publisher. this would cover 10 books in PDF format

https://www.meetup.com/pyladies-hamburg/events/302589793/
https://www.meetup.com/pyladies-berlin/events/302267360/

### Approvals

- [x] Approval 1: @discombobulateme 
- [x] Approval 2: <name-of-approver>

### Post Approval Actions

- [x] Email your invoice to: [invoice@python-verband.org](mailto:invoice@python-verband.org) with pyladies@python-verband.org in CC (you can find a template email in this [repo](/PyLadiesGermany/PySV_PyLadies_fund/blob/main/Docs/email_templates.md)).
- [x] Add the label `invoice submitted` to this issue
- [x] Once the invoice has been paid, add the label `invoice_paid` to this issue & move issue to completed requests

### Additional Information

We discussed this in the PyLadies Berlin orga meeting and agreed to proceed. It was mentioned that this request could cover a copy for the organisers as a thankyou for organising.

**Comment by sleepypioneer** [comment]
I have ordered a print version so wouldn't need a copy but @terezaif perhaps you want to reserve one for you and Ann Marie :)

**Comment by terezaif** [comment]
I also just got my print version 👯

**Comment by alanderex** [comment]
Requested payment details for transfer.

**Comment by alanderex** [comment]
Transfer was made.
