### ISSUE TITLE
[+ 300 EUR Donation] From Holidu

### ISSUE THREAD

**Issue by berlin-pyladies** [PyLadiesGermany/PySV_PyLadies_fund#26]
Donation made for work done by @sleepypioneer to fund.
![Donation Holidu __ Pyladies Berlin](https://github.com/user-attachments/assets/db531bd7-d8a6-4ab6-b518-ac345e3e32ed)

**Comment by terezaif** [comment]
Oh, this is great! Is there documentation on how people can donate?  So I can add to hh as well?

**Comment by sleepypioneer** [comment]
@terezaif  This was kind of a one-off, but in theory, they can donate to the PySV and say it's specifically for PyLadies, perhaps even specifically for a chapter and we just track it here for transparency. Could definitely be documented in our docs. One thing to note is they don't get an official charity receipt from the PySV.
