### ISSUE TITLE
[772,17 EUR] Approval Single Request: Travel Grant for PyCon DE ticket winners

### ISSUE THREAD

**Issue by berlin-pyladies** [PyLadiesGermany/PySV_PyLadies_fund#6]
Thank you for opening a request for funds. Please fill in the information below. If this is your first request we recommend reading the documentation in this repository beforehand. ***Note that only existing chapters or new chapters who have held at least one event and are known to the PyLadies Germany group may submit requests.***

This type of request **requires approval**, this means that once submitted you must wait for approval before making the purchase. As soon as the request is approved you can go ahead and submit the receipt for reimbursement. Reimbursement can be expected within.

After opening the ISSUE a Slack message will be posted on the global PyLadies Slack in channel [#city-germany-pysv-fund](https://pyladies.slack.com/archives/C06B761RX6X).

### Request Details
- **Chapter Name:**  Germany wide
- [x] I have also added the chapter name as a label on the issue
- **Name of person submitting request:** Jessica 
- **Slack Handle of the person submitting the request:** Jessica Greene
- **Amount in EURs being requested:** not fully sure maybe 800 EUR (see below)
#### Reason for request *(what the money will be spent on - this will be used for reporting)*:
We raffled tickets around Germany (both where we have chapters already and not), some of those folks who won might need support to attend in terms of travel. Could we offer a small amount to everyone or ask who needs it and then split it between them?

I would propose to limit it to those who won a ticket or come as a pyladies volunteer (so the 20 tickets).

## Approvals
*Two approvals are required for this request to be approved. Please add the label `approved` to this issue once there are two approvals.*

- [x] Approval 1: laysauchoa
- [x] Approval 2: discombobulateme

## Post Approval
**Invoice/Receipt submitted to the PySV:**
- [ ] Email your invoice to: [invoice@python-verband.org](mailto:invoice@python-verband.org)
- [ ] I have put pyladies@python-verband.org in CC (or sent a copy)
- [ ] Add the label `invoice submitted` to this issue
- [ ] Once the invoice has been paid, add the label `invoice_paid` to this issue & move issue to completed requests

**Additional Information:**

**Comment by laysauchoa** [comment]
@sleepypioneer I'd like to approve this so we can book something and get a better price. Wdyt?

**Comment by sleepypioneer** [comment]
Awesome, I would say it needs two approvals could you please add you name to the description as approval one and check the box.

@discombobulateme perhaps you are open to be approval 2?

I have already gone ahead and emailed those who won tickets to find out who is interested in a bed. This would then give us an idea if we're booking for 6 or 8 people.

On booking.com I can get a better price

This place  https://www.booking.com/Share-0d1wxpt is 772 (no cancellation possible though) for 8 in a room. Also its at Alex so the conference center can be walked to.

There are two women from India trying to come and this would also help them greatly. Any objections to including them?

**Comment by laysauchoa** [comment]
We can include them for sure :)

**Comment by berlin-pyladies** [comment]
Booked an 8-bed dormitory at the Generator Berlin from 21st to 25th April, the cost is 772.17EUR However I had a deal to get 72 EUR travel vouchers after the stay so I will only request 700 EUR reimbursement.

**Comment by berlin-pyladies** [comment]
Email for those who applied for a room.

> Dear XXX,
> 
> we have now booked a dormitory room with 8 beds at the [Generator Berlin](https://www.booking.com/hotel/de/one-80-hostels-berlin.en-gb.html?aid=866831&label=postbooking_confemail&sid=736c482682f059001d0e82afea032edf&dist=0&group_adults=8&group_children=0&keep_landing=1&no_rooms=1&sb_price_type=total&type=total&) from Sunday 21st to Thursday 25th of April especially for PyLadies, and want to confirm we have reserved one of the beds for you. This hostel is within walking distance of the BCC where the conference takes place and also central to the main Berlin Tourist attractions. Note the important details regarding the location below
> 
> We look forward to having you join us at the conference and are also planning some activities on the Sunday, including a city tour, we will keep you updated on those :D
> 
> If you have any questions in the meantime, please feel free to contact us,
> 
> Best wishes,
> Jessica & PyLadies Germany
> 
> Important Details
> - Breakfast is not included but can be bought for 8.50 EUR *note that the conference provides breakfast
> - The toilets are shared with other guests
> - Towels are not included but can be rented on-site for a surcharge of EUR 5 per towel. Alternatively, guests can bring their own.
> - Guests are required to show a photo identification and credit card upon check-in. (We will come with you for check-in) Please note that all Special Requests are subject to availability and additional charges may apply.
